# Generated by Django 3.2.5 on 2021-07-21 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.PositiveIntegerField(choices=[(0, 'Sin Responder'), (1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Regular'), (4, 'Alto'), (5, 'Muy Alto')], default=0, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
    ]
