# Generated by Django 3.2.5 on 2021-07-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20210721_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='like',
            field=models.PositiveIntegerField(choices=[(0, 'Sin respuesta'), (1, 'Like'), (2, 'Dislike')], default=0, verbose_name='Like'),
        ),
        migrations.AddField(
            model_name='question',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ranking'),
        ),
    ]
